/*
	*	PROYECTO I
    *	AUTOR: CARLOS FERNANDEZ JIMENEZ
	*	CURSO: BASES DE DATOS 2
	*   DESCRIPCION: CODIGO FUENTE PARA SQLSERVER
*/


---CREAR LA BASE DE DATOS-------------------------------------
GO
CREATE DATABASE FERNANDEZC
ON 
( NAME = FERNANDEZC_FILE01,
    FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\FERNANDEZC_FILE01.mdf',
    SIZE = 10,
    MAXSIZE = 50,
    FILEGROWTH = 5 
)
GO

---USAR LA BASE DE DATOS--------------------------------------
GO
USE FERNANDEZC
GO

---CREAR LAS TABLAS-------------------------------------------

--CREAR LA TABLA REGION
GO
CREATE TABLE REGION
(
	ID_REGION INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	NOMBRE_REGION VARCHAR(100) NOT NULL
)
GO

--CREAR LA TABLA PAIS
GO
CREATE TABLE PAIS
(
	ID_PAIS INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	NOMBRE_PAIS  VARCHAR(100) NOT NULL,
	ID_REGION INT NOT NULL,
	FOREIGN KEY (ID_REGION) REFERENCES REGION(ID_REGION)
)
GO

--CREAR LA TABLA LOCALIZACION
GO
CREATE TABLE LOCALIZACION
(
	ID_LOCALIZACION INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	DIRECCION  VARCHAR(320) NOT NULL,
	CODIGO_POSTAL VARCHAR(60) NOT NULL,
	CIUDAD VARCHAR(100) NOT NULL,
	PROVINCIA VARCHAR(100) NOT NULL,
	ID_PAIS INT NOT NULL,
	FOREIGN KEY (ID_PAIS) REFERENCES PAIS(ID_PAIS)
)
GO

--CREAR LA TABLA PUESTO
GO
CREATE TABLE PUESTO
(
	ID_PUESTO INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	TITULO_PUESTO VARCHAR(100) NOT NULL,
	SALARIO_MIN MONEY NOT NULL,
	SALARIO_MAX MONEY NOT NULL
)
GO

--CREAR LA TABLA DEPARTAMENTO
GO
CREATE TABLE DEPARTAMENTO
(
	ID_DEPARTAMENTO INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	NOMBRE_DEPARTAMENTO  VARCHAR(100) NOT NULL,
	ID_GERENTE INT,
	ID_LOCALIZACION INT NOT NULL
)
GO

--CREAR LA TABLA EMPLEADO
GO
CREATE TABLE EMPLEADO
(
	ID_EMPLEADO INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	NOMBRE  VARCHAR(100) NOT NULL,
	APELLIDO VARCHAR(100) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	TELEFONO VARCHAR(100) NOT NULL,
	FECHA_CONTRATACION DATE NOT NULL,
	SALARIO MONEY NOT NULL,
	POR_COMISION FLOAT NOT NULL,
	ID_PUESTO INT NOT NULL,
	ID_GERENTE INT,
	ID_DEPARTAMENTO INT NOT NULL,
	FOREIGN KEY (ID_PUESTO) REFERENCES PUESTO(ID_PUESTO),
	FOREIGN KEY (ID_GERENTE) REFERENCES EMPLEADO(ID_EMPLEADO),
	FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTO(ID_DEPARTAMENTO)
)
GO

--CREAR LA TABLA HISTORIAL PUESTO
GO
CREATE TABLE HISTORIAL_PUESTO
(
	ID_EMPLEADO INT NOT NULL,
	FECHA_INICIO DATE NOT NULL,
	ID_PUESTO INT NOT NULL,
	ID_DEPARTAMENTO INT NOT NULL,
	FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO(ID_EMPLEADO),
	FOREIGN KEY (ID_PUESTO) REFERENCES PUESTO(ID_PUESTO),
	FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTO(ID_DEPARTAMENTO)
)
GO